sudo: false

language: c

addons:
  apt:
    sources: &sources
      - hvr-ghc
    packages: &testdeps
      - expect
      - cppcheck
      - hscolour

matrix:
  include:
    # - env: BUILD="cabal 1.20" TASK="tests"
    #   # separate caches for different compiler versions
    #   # until https://github.com/travis-ci/travis-ci/issues/4393 is resolved
    #   compiler: "#GHC-7.6.3"
    #   addons:
    #     apt:
    #       sources: *sources
    #       packages:
    #         - *testdeps
    #         - ghc-7.6.3
    #         - cabal-install-1.20
    # - env: BUILD="cabal 1.20" TASK="tests"
    #   compiler: "#GHC-7.8.4"
    #   addons:
    #     apt:
    #       sources: *sources
    #       packages:
    #         - *testdeps
    #         - ghc-7.8.4
    #         - cabal-install-1.20
    # - env: BUILD="cabal 1.22" TASK="docs"
    #   compiler: "#GHC-7.10.3"
    #   addons:
    #     apt:
    #       sources: *sources
    #       packages:
    #         - *testdeps
    #         - ghc-7.10.3
    #         - cabal-install-1.22
    # - env: BUILD="cabal 1.22" TASK="tests"
    #   compiler: "#GHC-7.10.3"
    #   addons:
    #     apt:
    #       sources: *sources
    #       packages:
    #         - *testdeps
    #         - ghc-7.10.3
    #         - cabal-install-1.22
    - env: BUILD="cabal 1.24" TASK="docs"
      compiler: "#GHC-8.0.1"
      addons:
        apt:
          sources: *sources
          packages:
            - *testdeps
            - ghc-8.0.1
            - cabal-install-1.24
    - env: BUILD="cabal 1.24" TASK="tests"
      compiler: "#GHC-8.0.1"
      addons:
        apt:
          sources: *sources
          packages:
            - *testdeps
            - ghc-8.0.1
            - cabal-install-1.24
    - env: BUILD="stack" TASK="tests"
      compiler: "#GHC-8.0.1"
      addons:
        apt:
          sources: *sources
          packages:
            - *testdeps
            - ghc-8.0.1
    - env: BUILD="stack" TASK="tests"
      compiler: "#GHC-8.0.1"
      os: osx


cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/.stack

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

before_install:
  - source travis.sh
  - before_install_env

install:
  - install_version
  - install_dependencies

before_script:
  - before_script_dist

script:
  - script_configure
  - script_build
  - script_copy
  - script_register
  - script_task
  - script_benchmarks
#
