sudo: false

language: c

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.6.3
      - ghc-7.8.4
      - ghc-7.10.3
      - ghc-8.0.1
      - cabal-install-1.20
      - cabal-install-1.22
      - cabal-install-1.24
      # test dependencies
      - expect
      - cppcheck
      - hscolour

matrix:
  include:
    - env: CABALVER="1.20" GHCVER="7.6.3" TESTS="test_c"
      # separate caches for different compiler versions
      # until https://github.com/travis-ci/travis-ci/issues/4393 is resolved
      compiler: ": #GHC 7.6.3"
    - env: CABALVER="1.20" GHCVER="7.8.4" TESTS="test_c"
      compiler: ": #GHC 7.8.4"
    - env: CABALVER="1.22" GHCVER="7.10.3" TESTS="lib_doc doc"
      compiler: ": #GHC 7.10.3"
    - env: CABALVER="1.22" GHCVER="7.10.3" TESTS="test_js"
      compiler: ": #GHC 7.10.3"
    - env: CABALVER="1.22" GHCVER="7.10.3" TESTS="test_c"
      compiler: ": #GHC 7.10.3"
    - env: CABALVER="1.24" GHCVER="8.0.1" TESTS="lib_doc doc"
      compiler: ": #GHC 8.0.1"
    - env: CABALVER="1.24" GHCVER="8.0.1" TESTS="test_js"
      compiler: ": #GHC 8.0.1"
    - env: CABALVER="1.24" GHCVER="8.0.1" TESTS="test_c"
      compiler: ": #GHC 8.0.1"

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

before_install:
  - source travis.sh
  - before_install_env

install:
  - install_version
  - install_dependencies

before_script:
  - before_script_dist

script:
  - script_configure
  - script_build
  - script_copy
  - script_register
  - script_cppcheck
  - script_tests
  - script_benchmarks
#
