#!/usr/bin/env bash
set -ex

case "$1" in
  version)
    cabal --version
    ghc --version
    ;;
  unpack)
    if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
    then
      zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz > \
          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
    fi
    ;;
  update)
    travis_retry cabal update -v
    # Run build with 2 parallel jobs
    # The container environment reports 16 cores,
    # causing cabal's default configuration (jobs: $ncpus)
    # to run into the GHC #9221 bug which can result in longer build-times.
    sed -i -r 's/(^jobs:).*/\1 2/' $HOME/.cabal/config
    ;;
  install)
    cabal install -f FFI --only-dependencies --enable-tests --dry -v > installplan.txt
    sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
    if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
    then
      echo "cabal build-cache HIT";
      rm -rfv .ghc;
      cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
      cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
    else
      echo "cabal build-cache MISS";
      rm -rf $HOME/.cabsnap;
      mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
      cabal install -f FFI --only-dependencies --enable-tests;
    fi
    # snapshot package-db on cache miss
    if [ ! -d $HOME/.cabsnap ];
    then
      echo "snapshotting package-db to build-cache";
      mkdir $HOME/.cabsnap;
      cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
    fi
    ;;
  *)
    echo "No task called $1"
esac  

